config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  root to: "login#login"

  match 'simple', to: 'entries#new', entry_type: 'simple', as: 'simple_input', via: :get
  resource(:login, path: 'login', as: 'login', controller: 'login', only: [:login, :do_login]) do
    get '/', action: 'login', on: :member
    post '/', action: 'do_login', on: :member
  end
  match 'logout' => 'login#do_logout', as: :logout, via: [:get, :post]
  resource(:create_user, path: 'create_user', as: 'create_user', controller: 'login', only: [:create_user, :do_create_user]) do
    get '/', action: 'create_user', on: :member
    post '/', action: 'do_create_user', on: :member
  end
  match 'confirm_user' => 'login#confirmation', as: :confirm_user, via: :get

  scope 'months/:year/:month' do
    resources :entries
    resources :profit_losses
    resources :balance_sheets
  end

  scope 'current' do
    resources :entries, as: 'current_entries'
    resources :profit_losses, as: 'current_profit_losses'
    resources :balance_sheets, as: 'current_balance_sheets'
  end

  %w( tag mark keyword ).each do |s|
    scope "/#{s.pluralize}/:#{s}", as: s.to_sym do
      resources :entries do
        resource :confirmation_required
      end
    end
  end

  resources :entries do
    resource :confirmation_required
  end

  resource :account_status
  resource :confirmation_status
  resource :tag_status
  resources :entry_candidates
  namespace(:admin) do
    resources :users
  end

  namespace(:settings) do
    resources :accounts
    resources :credit_relations
    resource :user
  end

  namespace(:api) do
    resources :entries
    resources :accounts
    resource :session
  end

  namespace(:chart_data) do
    resources :assets
    resources :budgets
    resources :yearly_budgets
    resources :yearly_assets
  end

  resources :emojis
end

app/models/credit_relation.rb
# frozen_string_literal: true

class CreditRelation < ActiveRecord::Base
  belongs_to :user

  SETTLEMENT_DAYS = PAYMENT_DAYS = (1..28).map { |i| [i.to_s, i] } + [[I18n.t('label.final_day'), 99]]
  PAYMENT_MONTHS =  %w(label.same_month
                       label.next_month
                       label.month_after_next
                       label.two_month_after_next).map.with_index { |key, index| [I18n.t(key), index] }

  validate :validate_on_save
  validates :credit_account_id, uniqueness: true, numericality: true
  validates :payment_account_id, numericality: true
  validates :payment_month, inclusion: { in: 0..3 }
  validate :should_not_used_as_payment_account
  validate :should_not_used_as_credit_account

  def validate_on_save
    errors.add(:settlement_day, I18n.t('errors.messages.invalid')) if settlement_day < 1 || (settlement_day > 28 && settlement_day != 99)
    errors.add(:payment_day, I18n.t('errors.messages.invalid')) if payment_day < 1 || (payment_day > 28 && payment_day != 99)
    errors.add(:settlement_day, I18n.t('errors.messages.before_due')) if payment_month.zero? && payment_day < settlement_day
    errors.add(:credit_account_id, I18n.t('errors.messages.different_from')) if payment_account_id == credit_account_id
  end

  def should_not_used_as_payment_account
    crs_in_payments = user.credit_relations.where(payment_account_id: credit_account_id)
    crs_in_payments = crs_in_payments.where.not(id: id) unless new_record?
    errors.add(:credit_account_id, I18n.t('errors.messages.used_as_payment_account')) if crs_in_payments.any?
  end

  def should_not_used_as_credit_account
    crs_in_credits = user.credit_relations.where(credit_account_id: payment_account_id)
    crs_in_credits = crs_in_credits.where.not(id: id) unless new_record?
    errors.add(:payment_account_id, I18n.t('errors.messages.used_as_credit_account')) if crs_in_credits.any?
  end
end

app/controllers/settings/accounts_controller.rb
# frozen_string_literal: true

class Settings::AccountsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :required_login
  before_action :_retrieve_account_or_redirect!, only: %i[edit update destroy show]

  def index
    @type = (params[:type].presence || 'banking').to_sym
    unless %i[banking expense income].include?(@type)
      redirect_to login_url
      return
    end

    @accounts = @user.send(@type.to_s.pluralize.to_sym).to_a
    render layout: 'entries'
  end

  def create
    @type = (params[:type].presence || 'banking').to_sym

    @account = @user.send(@type.to_s.pluralize.to_sym).build name: params[:account_name], order_no: params[:order_no]
    @account.save!
    redirect_js_to settings_accounts_url(type: @type)
  rescue ActiveRecord::RecordInvalid
    render_js_error id: 'add_warning', errors: @account.errors, default_message: t('error.input_is_invalid')
  end

  def update
    name = params[:account_name]
    order_no = params[:order_no]
    bgcolor = params[:use_bgcolor] == '1' ? params[:bgcolor].presence : nil

    @account.update_attributes!(name: name, order_no: order_no, bgcolor: bgcolor)
    redirect_js_to settings_accounts_url(type: @account.type.underscore)
  rescue ActiveRecord::RecordInvalid
    render_js_error id: "account_#{@account.id}_warning", errors: @account.errors, default_message: t('error.input_is_invalid')
  end

  def destroy
    @account.destroy
    return if @account.errors.empty?

    render_js_error id: 'add_warning', errors: @account.errors.full_messages
  end

  private

  def _retrieve_account_or_redirect!
    @account = @user.accounts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_js_to login_url
  end
end

app/controllers/settings/credit_relations_controller.rb
# frozen_string_literal: true

class Settings::CreditRelationsController < ApplicationController
  before_action :required_login

  def index
    @credit_relations = @user.credit_relations.all
    render layout: 'entries'
  end

  def create
    @cr = @user.credit_relations.create!(credit_account_id: params[:credit_account_id],
                                         payment_account_id: params[:payment_account_id],
                                         settlement_day: params[:settlement_day],
                                         payment_month: params[:payment_month],
                                         payment_day: params[:payment_day])

    @credit_relations = @user.credit_relations.all
  rescue ActiveRecord::RecordInvalid => e
    render_js_error id: 'warning', errors: e.record.errors.full_messages, default_message: t('error.input_is_invalid')
  end

  def destroy
    @user.credit_relations.destroy(params[:id])
    @destroyed_id = params[:id]
    render 'destroy'
  rescue ActiveRecord::RecordNotFound
    @credit_relations = @user.credit_relations.all
    render 'no_record'
  end

  def edit
    @cr = @user.credit_relations.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_js_error id: 'warning', default_errors: t('error.no_data')
  end

  def update
    @cr = @user.credit_relations.find(params[:id])
    @cr.update_attributes!(credit_account_id: params[:credit_account_id],
                           payment_account_id: params[:payment_account_id],
                           settlement_day: params[:settlement_day],
                           payment_month: params[:payment_month],
                           payment_day: params[:payment_day])
  rescue ActiveRecord::RecordNotFound
    @credit_relations = @user.credit_relations.all
    render 'no_record'
  rescue ActiveRecord::RecordInvalid
    render_js_error id: "edit_warning_#{@cr.id}", errors: @cr.errors, default_message: t('error.input_is_invalid')
  end

  def show
    @cr = @user.credit_relations.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_js_to settings_credit_relations_url
  end
end

app/controllers/settings/users_controller.rb
# frozen_string_literal: true

class Settings::UsersController < ApplicationController
  before_action :required_login

  def show
    render layout: 'entries'
  end

  def update
    @user_to_change = User.find(@user.id)
    @user_to_change.update_attributes!(email: params[:email],
                                       password_plain: params[:password_plain],
                                       password_confirmation: params[:password_confirmation])
    session[:user_id] = @user.id
  rescue ActiveRecord::RecordInvalid
    render_js_error id: 'warning', errors: @user_to_change.errors, default_message: t('error.input_is_invalid')
  end
end

app/helpers/settings/credit_relations_helper.rb
# frozen_string_literal: true

module Settings
  module CreditRelationsHelper
    def localize_relative_month(relative_month)
      CreditRelation::PAYMENT_MONTHS.find { |pm| pm[1] == relative_month }[0]
    end
  end
end

app/views/settings/credit_relations/_edit.html.haml
:coffeescript
  $ ->
    $('#edit_form_#{@cr.id}')
      .bind("ajax:before", -> $('#edit_button_#{@cr.id}').attr("disabled", true))
      .bind("ajax:complete", -> $('#edit_button_#{@cr.id}').attr("disabled", false))
%div{ id: "credit_relation_#{@cr.id}" }
  = form_tag settings_credit_relation_path(@cr.id), remote: true, method: :put, id: "edit_form_#{@cr.id}", class: 'form-horizontal well' do
    .control-group
      %label.control-label{ for: 'credit_account_id' }= t('settings.credit_relations.credit_card')
      .controls= select_tag 'credit_account_id', options_for_select(@user.bank_accounts, @cr.credit_account_id.to_s), class: 'input-medium'
    .control-group
      %label.control-label{ for: 'payment_account_id' }= t('settings.credit_relations.account_to_draw')
      .controls= select_tag 'payment_account_id', options_for_select(@user.bank_accounts, @cr.payment_account_id.to_s), class: 'input-medium'
    .control-group
      %label.control-label{ for: 'settlement_day' }= t('settings.credit_relations.closing_date')
      .controls
        .input-prepend.input-append
          %span.add-on>= t('settings.credit_relations.monthly')
          = select_tag 'settlement_day', options_for_select(CreditRelation::SETTLEMENT_DAYS, @cr.settlement_day), class: 'input-small'
          %span.add-on>= t('label.day')
    .control-group
      %label.control-label{ for: 'payment_month' }= t('settings.credit_relations.due')
      .controls
        = select_tag 'payment_month', options_for_select(CreditRelation::PAYMENT_MONTHS, @cr.payment_month), class: 'input-small'
        .input-append
          = select_tag 'payment_day', options_for_select(CreditRelation::PAYMENT_DAYS, @cr.payment_day), class: 'input-small'
          %span.add-on>= t('label.day')
    .control-group
      .controls
        = submit_tag t('button.save'), id: "edit_button_#{@cr.id}", class: %w'btn btn-primary'
        = link_to t('link.cancel'), settings_credit_relation_path(@cr.id), remote: true, method: :get, class: 'btn'
        .warning{ id: "edit_warning_#{@cr.id}" }

app/views/settings/credit_relations/_show.html.haml
.cfg_credit_relation.row-fluid{ id: "credit_relation_#{cr.id}" }
  .cfg_credit_relation_name.span2= colored_account_name(cr.credit_account_id)
  .cfg_payment_relation_name.span2
    %strong.visible-phone= t('settings.credit_relations.account_to_draw')
    = colored_account_name(cr.payment_account_id)
  .cfg_settlement_day.span2
    %strong.visible-phone= t('settings.credit_relations.closing_date')
    #{t('settings.credit_relations.monthly')} #{h(cr.settlement_day == 99 ? t('settings.credit_relations.final_day') : cr.settlement_day.to_s + t('label.day'))}
  .cfg_payment_date.span2
    %strong.visible-phone= t('settings.credit_relations.due')
    = localize_relative_month(cr.payment_month)
    = cr.payment_day < 99 ? cr.payment_day.to_s + t('label.day') : t('settings.credit_relations.final_day')
  .cfg_credit_relation_operation.span1
    = link_to icon_edit, edit_settings_credit_relation_path(cr.id), remote: true, method: :get
    = link_to icon_destroy, settings_credit_relation_path(cr.id), remote: true, method: :delete, confirm: t('message.delete_really')

app/views/settings/credit_relations/create.js.haml
! $("#warning").html('');
! $("#warning").removeAttr("class");
! $("#credit_relations").html('');
- @credit_relations.each do |cr|
  ! $("#credit_relations").append("#{j(render(partial: 'show', locals: { cr: cr }))}");
= highlight("#credit_relation_#{@cr.id} div")

app/views/settings/credit_relations/destroy.js.haml
! $("#warning").html('');
! $("#warning").removeAttr("class");
= fadeout_and_remove("#credit_relation_#{@destroyed_id}")

app/views/settings/credit_relations/edit.js.haml
! $("#credit_relation_#{@cr.id}").replaceWith("#{j render('edit')}");
! $("#warning").html('');

app/views/settings/credit_relations/index.html.haml
:coffeescript
  $ ->
    $("#add_form")
      .bind("ajax:before", -> $('#add_button').attr("disabled", true))
      .bind("ajax:complete", -> $('#add_button').attr("disabled", false))
.row
  .span12
    .cfg_credit_relation_list
      %h3= t('.register_credit_relation')
      = form_tag settings_credit_relations_path, remote: true, method: :post, id: 'add_form', class: 'form-horizontal well' do
        .control-group
          %label.control-label{ for: 'credit_account_id' }= t('settings.credit_relations.credit_card')
          .controls= select_tag 'credit_account_id', options_for_select(@user.bank_accounts), class: 'input-medium'
        .control-group
          %label.control-label{ for: 'payment_account_id' }= t('settings.credit_relations.account_to_draw')
          .controls= select_tag 'payment_account_id', options_for_select(@user.bank_accounts), class: 'input-medium'
        .control-group
          %label.control-label{ for: 'settlement_day' }= t('settings.credit_relations.closing_date')
          .controls
            .input-prepend.input-append
              %span.add-on>= t('settings.credit_relations.monthly')
              = select_tag 'settlement_day', options_for_select(CreditRelation::SETTLEMENT_DAYS), class: 'input-small'
              %span.add-on>= t('label.day')
        .control-group
          %label.control-label{ for: 'payment_month' }= t('settings.credit_relations.due')
          .controls
            = select_tag 'payment_month', options_for_select(CreditRelation::PAYMENT_MONTHS), class: 'input-small'
            .input-append
              = select_tag 'payment_day', options_for_select(CreditRelation::PAYMENT_DAYS), class: 'input-small'
              %span.add-on>= t('label.day')
        .control-group
          .controls
            = submit_tag t('button.register'), id: 'add_button', class: 'btn btn-primary'
            .warning#warning
      %h3= t('label.list_update_delete')
      .cfg_credit_relations_header.row-fluid#credit_relations_headers
        .cfg_credit_relation_name.cfg_credit_relation_header.span2.hidden-phone= t('settings.credit_relations.credit_card')
        .cfg_payment_relation_name.cfg_credit_relation_header.span2.hidden-phone= t('settings.credit_relations.account_to_draw')
        .cfg_settlement_day.cfg_credit_relation_header.span2.hidden-phone= t('settings.credit_relations.closing_date')
        .cfg_payment_date.cfg_credit_relation_header.span2.hidden-phone= t('settings.credit_relations.due')
        .cfg_credit_relation_operation.cfg_credit_relation_header.span1.hidden-phone
      #credit_relations
        - @credit_relations.each do |cr|
          = render partial: 'show', locals: { cr: cr }

app/views/settings/credit_relations/no_record.js.haml
! $("#warning").html('');
! $("#credit_relations").html('');
- @credit_relations.each do |cr|
  ! $("#credit_relations").append("#{j render(partial: 'show', locals: { cr: cr })}");

app/views/settings/credit_relations/show.js.haml
! $("#credit_relation_#{@cr.id}").replaceWith("#{j render(partial: 'show', locals: { cr: @cr })}");

app/views/settings/credit_relations/update.js.haml
! $("#credit_relation_#{@cr.id}").replaceWith("#{j render(partial: 'show', locals: { cr: @cr })}");
= highlight("#credit_relation_#{@cr.id} div")
! $("#warning").html('');
! $("#warning").removeAttr("class");