config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  root to: "login#login"

  match 'simple', to: 'entries#new', entry_type: 'simple', as: 'simple_input', via: :get
  resource(:login, path: 'login', as: 'login', controller: 'login', only: [:login, :do_login]) do
    get '/', action: 'login', on: :member
    post '/', action: 'do_login', on: :member
  end
  match 'logout' => 'login#do_logout', as: :logout, via: [:get, :post]
  resource(:create_user, path: 'create_user', as: 'create_user', controller: 'login', only: [:create_user, :do_create_user]) do
    get '/', action: 'create_user', on: :member
    post '/', action: 'do_create_user', on: :member
  end
  match 'confirm_user' => 'login#confirmation', as: :confirm_user, via: :get

  scope 'months/:year/:month' do
    resources :entries
    resources :profit_losses
    resources :balance_sheets
  end

  scope 'current' do
    resources :entries, as: 'current_entries'
    resources :profit_losses, as: 'current_profit_losses'
    resources :balance_sheets, as: 'current_balance_sheets'
  end

  %w( tag mark keyword ).each do |s|
    scope "/#{s.pluralize}/:#{s}", as: s.to_sym do
      resources :entries do
        resource :confirmation_required
      end
    end
  end

  resources :entries do
    resource :confirmation_required
  end

  resource :account_status
  resource :confirmation_status
  resource :tag_status
  resources :entry_candidates
  namespace(:admin) do
    resources :users
  end

  namespace(:settings) do
    resources :accounts
    resources :credit_relations
    resource :user
  end

  namespace(:api) do
    resources :entries
    resources :accounts
    resource :session
  end

  namespace(:chart_data) do
    resources :assets
    resources :budgets
    resources :yearly_budgets
    resources :yearly_assets
  end

  resources :emojis
end

app/models/account.rb
# frozen_string_literal: true

class Account < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  extend Memoist

  belongs_to :user
  has_one :payment_relation, foreign_key: :credit_account_id, class_name: 'CreditRelation'
  has_many :credit_relations, foreign_key: :payment_account_id, class_name: 'CreditRelation'

  before_validation :trim_bgcolor_if_needed
  before_destroy :error_if_items_exist
  before_destroy :error_if_credit_relations_exist

  after_save :clear_cache

  validates :name, presence: true, length: { in: 1..255 }
  validates :order_no, presence: true, format: { with: /\A\d+\z/ }
  validates :type, presence: true, format: { with: /\ABanking\z|\AIncome\z|\AExpense\z/ }
  validates :bgcolor, format: { with: /\A[0-9a-f]{6}/i, allow_blank: true }

  scope :active, -> { where(active: true) }

  default_scope { order('order_no') }

  def trim_bgcolor_if_needed
    self.bgcolor = bgcolor.gsub('#', '') if bgcolor =~ /^#/
  end

  def credit_due_date(action_date)
    cr = payment_relation
    if cr
      earliest_month = cr.payment_month.months.since(action_date)
      due_month = action_date.day <= cr.settlement_day ? earliest_month : 1.month.since(earliest_month)
      due_date = cr.payment_day == 99 ? due_month.end_of_month : Date.new(due_month.year, due_month.month, cr.payment_day)
    end
    due_date
  end

  class << self
    # 特定の日付までの残高を取得する
    # my_id でitemのIDを指定すると、そのItemが除外される。また、
    # dateと、my_idに該当するitemのaction_dateが同一の場合、
    # dateと同じ日のitemデータのうち、my_idよりidがおおきいものは残高計算から除外する
    #
    def asset(user, account_id, date, my_id = nil)
      my_item = my_id ? user.items.find_by_id(my_id) : nil

      # amountの算出
      # 前月までのassetを算出
      asset = asset_to_last_month(user, account_id, date, except: my_item)
      # 今月のassetの変化を算出
      asset += if my_item.nil?
                 asset_beginning_of_month_to_date(user, account_id, date)
               elsif my_item.action_date == date
                 asset_to_item_of_this_month_except(user, account_id, date, my_id)
               else
                 asset_to_date_of_this_month_except(user, account_id, date, my_id)
               end

      asset
    end

    def asset_of_month(user, account_ids, month)
      user.monthly_profit_losses.where(account_id: account_ids).where('month <= ?', month.beginning_of_month).sum(:amount)
    end
  end

  private

  def error_if_items_exist
    items_table = Item.arel_table
    item = Item.where(items_table[:from_account_id].eq(id).or(items_table[:to_account_id].eq(id))).first
    errors[:base] << I18n.t('error.already_used_account') + "#{I18n.l(item.action_date)} #{item.name} #{number_to_currency(item.amount)}" if item

    throw :abort unless errors.empty?
  end

  def clear_cache
    Rails.cache.delete_matched(/^user_#{user_id}/)
  end

  def error_if_credit_relations_exist
    cr_table = CreditRelation.arel_table
    credit_rel = CreditRelation.where(cr_table[:credit_account_id].eq(id).or(cr_table[:payment_account_id].eq(id))).first
    errors[:base] << I18n.t('error.already_has_relation_to_credit') if credit_rel

    throw :abort unless errors.empty?
  end

  class << self
    def asset_to_last_month(user, account_id, date, options = {})
      # 今月以前はplから抽出してしまうため、SQLではoption[:except]で指定されたitemの.amountを
      # 除外できない
      asset_of_month(user, account_id, date.beginning_of_month.months_ago(1)) +
        correlate_for_item(account_id, options[:except], date.beginning_of_month)
    end

    def correlate_for_item(account_id, item, this_month)
      if item && item.action_date < this_month
        item.from_account_id == account_id ? item.amount : (-1 * item.amount)
      else
        0
      end
    end

    def asset_to_date_of_this_month_except(user, account_id, date, item_id)
      user.items.action_date_between(date.beginning_of_month, date).where.not(id: item_id).scoping do
        expense = Item.where(from_account_id: account_id).sum(:amount)
        income = Item.where(to_account_id: account_id).sum(:amount)
        income - expense
      end
    end

    def asset_to_item_of_this_month_except(user, account_id, date, item_id)
      user.items.where('(action_date >= ? and action_date < ? and id <> ?) or (action_date = ? and id < ?)', date.beginning_of_month, date, item_id, date, item_id).scoping do
        expense = Item.where(from_account_id: account_id).sum(:amount)
        income = Item.where(to_account_id: account_id).sum(:amount)
        income - expense
      end
    end

    def asset_beginning_of_month_to_date(user, account_id, date)
      user.items.action_date_between(date.beginning_of_month, date).scoping do
        expense = Item.where(from_account_id: account_id).sum(:amount)
        income = Item.where(to_account_id: account_id).sum(:amount)
        income - expense
      end
    end
  end
end

app/controllers/api/accounts_controller.rb
# frozen_string_literal: true

class Api::AccountsController < ApplicationController
  include Api::Auth
  include ActionView::Helpers::NumberHelper
  respond_to :json

  def index
    accounts = Rails.cache.fetch("user_#{@user.id}_api_accounts") do
      accts = []
      %w(bankings incomes expenses).each do |type|
        accts +=  @user.send(type.to_s.to_sym)
      end
      accts
    end
    render locals: { accounts: accounts }
  end
end

app/controllers/settings/accounts_controller.rb
# frozen_string_literal: true

class Settings::AccountsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :required_login
  before_action :_retrieve_account_or_redirect!, only: %i[edit update destroy show]

  def index
    @type = (params[:type].presence || 'banking').to_sym
    unless %i[banking expense income].include?(@type)
      redirect_to login_url
      return
    end

    @accounts = @user.send(@type.to_s.pluralize.to_sym).to_a
    render layout: 'entries'
  end

  def create
    @type = (params[:type].presence || 'banking').to_sym

    @account = @user.send(@type.to_s.pluralize.to_sym).build name: params[:account_name], order_no: params[:order_no]
    @account.save!
    redirect_js_to settings_accounts_url(type: @type)
  rescue ActiveRecord::RecordInvalid
    render_js_error id: 'add_warning', errors: @account.errors, default_message: t('error.input_is_invalid')
  end

  def update
    name = params[:account_name]
    order_no = params[:order_no]
    bgcolor = params[:use_bgcolor] == '1' ? params[:bgcolor].presence : nil

    @account.update_attributes!(name: name, order_no: order_no, bgcolor: bgcolor)
    redirect_js_to settings_accounts_url(type: @account.type.underscore)
  rescue ActiveRecord::RecordInvalid
    render_js_error id: "account_#{@account.id}_warning", errors: @account.errors, default_message: t('error.input_is_invalid')
  end

  def destroy
    @account.destroy
    return if @account.errors.empty?

    render_js_error id: 'add_warning', errors: @account.errors.full_messages
  end

  private

  def _retrieve_account_or_redirect!
    @account = @user.accounts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_js_to login_url
  end
end

app/controllers/settings/credit_relations_controller.rb
# frozen_string_literal: true

class Settings::CreditRelationsController < ApplicationController
  before_action :required_login

  def index
    @credit_relations = @user.credit_relations.all
    render layout: 'entries'
  end

  def create
    @cr = @user.credit_relations.create!(credit_account_id: params[:credit_account_id],
                                         payment_account_id: params[:payment_account_id],
                                         settlement_day: params[:settlement_day],
                                         payment_month: params[:payment_month],
                                         payment_day: params[:payment_day])

    @credit_relations = @user.credit_relations.all
  rescue ActiveRecord::RecordInvalid => e
    render_js_error id: 'warning', errors: e.record.errors.full_messages, default_message: t('error.input_is_invalid')
  end

  def destroy
    @user.credit_relations.destroy(params[:id])
    @destroyed_id = params[:id]
    render 'destroy'
  rescue ActiveRecord::RecordNotFound
    @credit_relations = @user.credit_relations.all
    render 'no_record'
  end

  def edit
    @cr = @user.credit_relations.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_js_error id: 'warning', default_errors: t('error.no_data')
  end

  def update
    @cr = @user.credit_relations.find(params[:id])
    @cr.update_attributes!(credit_account_id: params[:credit_account_id],
                           payment_account_id: params[:payment_account_id],
                           settlement_day: params[:settlement_day],
                           payment_month: params[:payment_month],
                           payment_day: params[:payment_day])
  rescue ActiveRecord::RecordNotFound
    @credit_relations = @user.credit_relations.all
    render 'no_record'
  rescue ActiveRecord::RecordInvalid
    render_js_error id: "edit_warning_#{@cr.id}", errors: @cr.errors, default_message: t('error.input_is_invalid')
  end

  def show
    @cr = @user.credit_relations.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_js_to settings_credit_relations_url
  end
end

app/controllers/settings/users_controller.rb
# frozen_string_literal: true

class Settings::UsersController < ApplicationController
  before_action :required_login

  def show
    render layout: 'entries'
  end

  def update
    @user_to_change = User.find(@user.id)
    @user_to_change.update_attributes!(email: params[:email],
                                       password_plain: params[:password_plain],
                                       password_confirmation: params[:password_confirmation])
    session[:user_id] = @user.id
  rescue ActiveRecord::RecordInvalid
    render_js_error id: 'warning', errors: @user_to_change.errors, default_message: t('error.input_is_invalid')
  end
end

app/helpers/settings/credit_relations_helper.rb
# frozen_string_literal: true

module Settings
  module CreditRelationsHelper
    def localize_relative_month(relative_month)
      CreditRelation::PAYMENT_MONTHS.find { |pm| pm[1] == relative_month }[0]
    end
  end
end

app/views/settings/accounts/_add.html.haml
:coffeescript
  $ ->
    $("#create_form")
      .bind("ajax:before", -> $('#submit_button').attr("disabled", true))
      .bind("ajax:complete", -> $('#submit_button').attr("disabled", false))
= form_tag settings_accounts_path, remote: true, method: :post, id: 'create_form', class: 'form-horizontal well' do
  .control-group
    %label.control-label{ for: 'account_name' }= t("settings.accounts.#{@type}_account")
    .controls= text_field_tag :account_name, nil, class: 'input-medium', placeholder: 'Wallet, Citi bank, Food'
  .control-group
    %label.control-label{ for: 'order_no' }= t('label.position')
    .controls
      = text_field_tag :order_no, nil, class: 'input-small', placeholder: '10'
      = hidden_field_tag :type, @type
  .control-group
    .controls
      = submit_tag t('button.register'), id: 'submit_button', class: 'btn btn-primary'
.warning#add_warning

app/views/settings/accounts/_edit.html.haml
:coffeescript
  $ ->
    $('#colorpicker_#{@account.id}').farbtastic('#colorfield_#{@account.id}')
    $("#edit_form_#{@account.id}")
      .bind("ajax:before", -> $('#edit_button_#{@account.id}').attr('disabled', true))
      .bind("ajax:complete", -> $('#edit_button_#{@account.id}').attr('disabled', false))
%div{ id: "account_#{@account.id}" }
  = form_tag settings_account_path(@account.id), method: :put, remote: true, id: "edit_form_#{@account.id}", class: %w(form-horizontal well) do
    .control-group
      %label.control-label{ for: 'account_name' }= t("settings.accounts.#{@account.type.underscore}_account")
      .controls= text_field_tag :account_name, @account.name, class: 'input-medium'
    .control-group
      %label.control-label{ for: 'order_no' }= t('label.position')
      .controls= text_field_tag :order_no, @account.order_no, class: 'input-small'
    .control-group
      %label.control-label{ for: 'use_bgcolor' }= t('.use_bgcolor')
      .controls
        = check_box_tag :use_bgcolor, '1', @account.bgcolor.present?, id: "use_bgcolor_#{@account.id}"
        = hidden_field_tag :bgcolor, @account.bgcolor.nil? ? '#ffffff' : "##{@account.bgcolor}", id: "colorfield_#{@account.id}"
        %span{ id: "colorpicker_#{@account.id}" }
    .control-group
      .controls
        = submit_tag t('button.save'), id: "edit_button_#{@account.id}", class: %w'btn btn-primary'
        = link_to t('link.cancel'), settings_account_path(@account.id), remote: true, method: :get, class: 'btn'
    .row-fluid
      .warning{ id: "account_#{@account.id}_warning" }

app/views/settings/accounts/_show.html.haml
.cfg_account.row-fluid{ id: "account_#{account.id}" }
  .cfg_account_name.span2
    - if account.bgcolor?
      = colored_account_name(account.id)
    - else
      = account.name
  .cfg_account_order.span1
    = account.order_no
  .cfg_account_operation.span1
    = link_to icon_edit, edit_settings_account_path(account.id), method: :get, remote: true
    = link_to icon_destroy, settings_account_path(account.id), method: :delete, data: { confirm: t('message.delete_really') }, remote: true

app/views/settings/accounts/destroy.js.haml
= fadeout_and_remove("#account_#{@account.id}")
! $("#add_warning").html('#{t('message.delete_successfully')}');

app/views/settings/accounts/edit.js.haml
:plain
  $("#account_#{@account.id}").replaceWith("#{j render('edit')}");
  this.accounts.toggleColorPicker("#{@account.id}");

app/views/settings/accounts/index.html.haml
- provide :append_head do
  = javascript_include_tag 'settings/accounts'
  = javascript_include_tag 'farbtastic'
  = stylesheet_link_tag 'farbtastic'
.row
  .span12
    .cfg_account_list
      #input_add= render 'add'
      #accounts
        .cfg_account.row-fluid
          .cfg_account_name.cfg_account_header.span2.hidden-phone= t("settings.accounts.#{@type}_account")
          .cfg_account_order.cfg_account_header.span1.hidden-phone= t('label.position')
          .cfg_account_operation.cfg_account_header.span1.hidden-phone &nbsp;
        - @accounts.each do |account|
          = render partial: 'show', locals: { account: account }

app/views/settings/accounts/show.js.haml
! $("#account_#{@account.id}").replaceWith("#{j render(partial: 'show', locals: { account: @account })}")