config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  root to: "login#login"

  match 'simple', to: 'entries#new', entry_type: 'simple', as: 'simple_input', via: :get
  resource(:login, path: 'login', as: 'login', controller: 'login', only: [:login, :do_login]) do
    get '/', action: 'login', on: :member
    post '/', action: 'do_login', on: :member
  end
  match 'logout' => 'login#do_logout', as: :logout, via: [:get, :post]
  resource(:create_user, path: 'create_user', as: 'create_user', controller: 'login', only: [:create_user, :do_create_user]) do
    get '/', action: 'create_user', on: :member
    post '/', action: 'do_create_user', on: :member
  end
  match 'confirm_user' => 'login#confirmation', as: :confirm_user, via: :get

  scope 'months/:year/:month' do
    resources :entries
    resources :profit_losses
    resources :balance_sheets
  end

  scope 'current' do
    resources :entries, as: 'current_entries'
    resources :profit_losses, as: 'current_profit_losses'
    resources :balance_sheets, as: 'current_balance_sheets'
  end

  %w( tag mark keyword ).each do |s|
    scope "/#{s.pluralize}/:#{s}", as: s.to_sym do
      resources :entries do
        resource :confirmation_required
      end
    end
  end

  resources :entries do
    resource :confirmation_required
  end

  resource :account_status
  resource :confirmation_status
  resource :tag_status
  resources :entry_candidates
  namespace(:admin) do
    resources :users
  end

  namespace(:settings) do
    resources :accounts
    resources :credit_relations
    resource :user
  end

  namespace(:api) do
    resources :entries
    resources :accounts
    resource :session
  end

  namespace(:chart_data) do
    resources :assets
    resources :budgets
    resources :yearly_budgets
    resources :yearly_assets
  end

  resources :emojis
end

app/controllers/api/entries_controller.rb
# frozen_string_literal: true

class Api::EntriesController < ApplicationController
  include Api::Auth
  include Common::Entries
  respond_to :json

  def index
    super
    render locals: { items: @items }
  rescue ArgumentError
    head :not_acceptable
  end

  def show
    _json_action do
      super
      render locals: { item: @item }
    end
  end

  def create
    _json_action do
      super
      render locals: { item: @item, updated_item_ids: @updated_item_ids }, status: :created, location: api_entries_url(@item.id)
    end
  end

  def update
    _json_action do
      super
      render locals: { item: @item, updated_item_ids: @updated_item_ids }, status: :ok
    end
  end

  def destroy
    _json_action do
      super
      render locals: { item: @item, updated_item_ids: @updated_item_ids, deleted_item_ids: @deleted_item_ids }, status: :ok
    end
  end

  private

  def _json_action(&block)
    block.call
  rescue SyntaxError
    errors = [t('error.amount_is_invalid')]
    render json: { errors: errors }.to_json, status: :not_acceptable
  rescue InvalidDate # in case the date in params has invalid format
    errors = [t('error.date_is_invalid')]
    render json: { errors: errors }.to_json, status: :not_acceptable
  rescue ActiveRecord::RecordNotFound
    head :not_found
  rescue ActiveRecord::RecordInvalid => e
    errors = e.record.errors.full_messages
    render json: { errors: errors }.to_json, status: :not_acceptable
  end
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

class EntriesController < ApplicationController
  include Common::Entries
  before_action :required_login

  def index
    super
    case
    when params[:remaining]
      template = 'index_for_remaining'
    when !params[:filter_account_id].nil?
      # when "No filter" is selected, params[:filter_...] is ""
      # so it should not use blank?/present? in the condition
      template = 'index_with_filter_account_id'
    when @tag.present? || @keyword.present?
      template = 'index_with_tag_keyword'
    when @mark.present?
      template = 'index_with_mark'
    else
      @new_item = Item.new { |item| item.action_date = _default_action_date(displaying_month) }
      template = 'index'
    end
    render template
  rescue ArgumentError # in case the date in params has invalid format
    respond_to do |format|
      format.js { redirect_js_to current_entries_url }
      format.html { redirect_to current_entries_url }
    end
  end

  def new
    if params[:entry_type] == 'simple'
      _new_simple
    else
      _new_entry(params[:entry_type])
    end
  end

  def show
    _xhr_action('warning') do
      super
    end
  end

  def edit
    _xhr_action('warning') do
      @item = @user.items.find(params[:id])
    end
  end

  def destroy
    _xhr_action('warning') do
      super
      render 'destroy', locals: { item: @item, deleted_ids: @deleted_item_ids, updated_items: @updated_items }
    end
  end

  def create
    _xhr_action('warning') do
      super

      if params[:only_add]
        render 'create_item_simple', locals: { item: @item }
      else
        @items = get_items(month: displaying_month)
        template = @item.adjustment? ? 'create_adjustment' : 'create_item'
        render template, locals: { item: @item, items: @items, updated_item_ids: @updated_item_ids }
      end
    end
  end

  def update
    _xhr_action("item_warning_#{params[:id]}") do
      super
      items = get_items(month: displaying_month)
      render 'update', locals: { item: @item, items: items, updated_item_ids: @updated_item_ids }
    end
  end

  private

  # this method is called when a link in the field of adding regular item or adjustment.
  # which switches forms each other.
  def _new_entry(entry_type)
    action_date = _get_date_by_specific_year_and_month_or_today(params[:year], params[:month])
    item_class = entry_type == 'adjustment' ? Adjustment : GeneralItem
    @item = item_class.new(action_date: action_date)
    render 'new'
  end

  def _new_simple
    @data = {
      authenticity_token: form_authenticity_token,
      year: today.year,
      month: today.month,
      day: today.day,
      from_accounts: from_accounts,
      to_accounts: to_accounts
    }

    render 'new_simple', layout: false
  end

  def _xhr_action(warning_selector, &block)
    block.call
  rescue ActiveRecord::RecordNotFound
    redirect_js_to current_entries_url
  rescue InvalidDate
    render_js_error id: warning_selector, default_message: t('error.date_is_invalid')
  rescue SyntaxError
    render_js_error id: warning_selector, default_message: t('error.amount_is_invalid')
  rescue ActiveRecord::RecordInvalid => e
    render_js_error(id: warning_selector, errors: e.record.errors.full_messages, default_message: t('error.input_is_invalid'))
  end
end

app/helpers/entries_helper.rb
# frozen_string_literal: true

module EntriesHelper
  def link_to_confirmation_required(item_id, required, options = {})
    label = required ? icon_confirmation : icon_no_confirmation
    css_class = required ? 'item_confirmation_required' : 'item_confirmation_not_required'
    tag = options[:tag]
    mark = options[:mark]
    keyword = options[:keyword]
    url = if tag
            tag_entry_confirmation_required_path(tag, item_id, confirmation_required: !required)
          elsif mark
            mark_entry_confirmation_required_path(mark, item_id, confirmation_required: !required)
          elsif keyword
            keyword_entry_confirmation_required_path(keyword, item_id, confirmation_required: !required)
          else
            entry_confirmation_required_path(item_id, confirmation_required: !required)
          end

    link_to label, url, remote: true, method: :put, class: css_class
  end

  def relative_path(item_id)
    item = @user.items.find(item_id)
    relative = item.parent_item || item.child_item
    relative ? entries_path(year: relative.action_date.year, month: relative.action_date.month, anchor: "item_#{relative.id}") : nil
  end

  def link_to_edit(item, enabled = true)
    if enabled
      link_to icon_edit, edit_entry_path(item.action_date.year, item.action_date.month, item.id), remote: true, method: :get, class: 'edit_link'
    else
      icon_edit(enabled)
    end
  end

  def link_to_destroy(item, enabled = true)
    if enabled
      link_to icon_destroy, entry_path(item.action_date.year, item.action_date.month, item.id), remote: true, method: :delete, data: { confirm: t('message.delete_really') }
    else
      icon_destroy(enabled)
    end
  end

  def link_to_show(item, enabled = true)
    if enabled
      link_to icon_show, entries_path(item.action_date.year, item.action_date.month, anchor: "item_#{item.id}"), class: 'show_link'
    else
      icon_show(enabled)
    end
  end

  def icon_confirmation
    '<i class="icon-star item_confirmation_required"></i>'.html_safe
  end

  def icon_no_confirmation
    '<i class="icon-star-empty item_confirmation_not_required"></i>'.html_safe
  end

  def link_to_tags(item)
    if item.tags.present?
      ('[' + item.tags.sort_by(&:name).map { |tag| link_to_tag(tag) }.join(' ') + ']').html_safe
    else
      ''
    end
  end

  def item_row_class(item)
    row_class = if item.adjustment?
                  'item_adjustment'
                elsif item.parent_id
                  'item_move'
                elsif @user.income_ids.include?(item.from_account_id)
                  'item_income'
                elsif @user.banking_ids.include?(item.from_account_id) && @user.banking_ids.include?(item.to_account_id)
                  'item_move'
                else
                  ''
                end
    row_class
  end

  def item_row_name(item)
    item_name = if item.adjustment?
                  (t('label.adjustment').decorate + ' ' + number_to_currency(item.adjustment_amount)).html_safe
                elsif item.parent_id
                  link_body = "#{l(item.parent_item.action_date, format: :short)} #{item.parent_item.name.decorate}".html_safe
                  "#{t('entries.item.deposit')} (#{link_to link_body, relative_path(item.id)})".html_safe
                elsif item.child_item
                  link_body = "#{l(item.child_item.action_date, format: :short)} #{t('entries.item.deposit')}".html_safe
                  "#{item.name.decorate} (#{link_to link_body, relative_path(item.id)})".html_safe
                else
                  item.name.decorate
                end

    item_name
  end

  def item_row_confirmation_required(item, tag, mark, keyword)
    confirmation_required = if item.adjustment?
                              ''
                            elsif item.parent_id
                              link_to_confirmation_required(item.id, item.parent_item.confirmation_required?, tag: tag, mark: mark, keyword: keyword)
                            else
                              link_to_confirmation_required(item.id, item.confirmation_required?, tag: tag, mark: mark, keyword: keyword)
                            end

    confirmation_required
  end

  def item_row_from_account(item)
    from_account = if item.adjustment?
                     item.amount < 0 ? colored_account_name(item.to_account_id) : '(' + t('label.adjustment') + ')'
                   else
                     colored_account_name(item.from_account_id)
                   end
    from_account
  end

  def item_row_to_account(item)
    to_account = if item.adjustment?
                   item.amount >= 0 ? colored_account_name(item.to_account_id) : '(' + t('label.adjustment') + ')'
                 else
                   colored_account_name(item.to_account_id)
                 end
    to_account
  end

  def item_row_twitter_button(item)
    if item.adjustment? || item.parent_id
      ''
    else
      tweet_button(item)
    end
  end

  def item_row_operation(item, only_show = false)
    if only_show
      link_to_show(item)
    else
      (item_row_twitter_button(item) +
       link_to_edit(item) +
       link_to_destroy(item, item.parent_id.blank?)).html_safe
    end
  end
end

app/views/entries/_edit_adjustment.html.haml
:coffeescript
  $ ->
    $("#edit_#{item.id}_form")
      .bind("ajax:before", ->
        $('#edit_button_#{item.id}').attr 'disabled', true
        $('#item_operation_#{item.id}').hide()
        $('#item_operation_loading_#{item.id}').show())
      .bind("ajax:complete", ->
        $('#edit_button_#{item.id}').attr 'disabled', false
        $('#item_operation_loading_#{item.id}').hide()
        $('#item_operation_#{item.id}').show())
.item{ id: "item_#{item.id}" }
  = form_for item, as: :entry, url: entry_path(displaying_month.year, displaying_month.month, item.id), remote: true, method: :put, html: { id: "edit_#{item.id}_form", class: 'well' } do |f|
    = f.hidden_field :action_date, value: l(item.action_date)
    .row-fluid.input-row
      = t('entries.adjustment_explanation')
    .row-fluid.input-row
      = l(item.action_date)
    .row-fluid.input-row
      = f.select :to_account_id, @user.bank_accounts, {}, class: 'input-medium'
      %span.input-append
        = f.text_field :adjustment_amount, size: 10, style: 'text-align: right;', class: %w'input-small adjustment_amount'
        %span.add-on>= t('number.currency.format.unit')
      = f.text_field :tag_list, placeholder: t('placeholder.tag'), class: %w'input-medium tag_list'
      %span{ id: "item_operation_#{h item.id}" }
        = f.submit t('button.save'), id: "edit_button_#{item.id}", class: %w'btn btn-primary'
        = link_to t('link.cancel'), entry_path(displaying_month.year, displaying_month.month, item.id), remote: true, method: :get, class: 'btn'
      %span{ id: "item_operation_loading_#{h item.id}", style: 'display:none;' }= image_tag 'loading.gif', alt: 'loading...'
      = f.hidden_field 'entry_type', value: 'adjustment'
    .row-fluid.input-row
      %div{ id: "item_warning_#{item.id}" }

app/views/entries/_edit_child_item.html.haml
:coffeescript
  $ ->
    $('#edit_#{item.id}_form').bind "ajax:before", ->
      $('#edit_button_#{item.id}').attr 'disabled', true
      $('#item_operation_#{item.id}').hide()
      $('#item_operation_loading_#{item.id}').show()
    $('#edit_#{item.id}_form').bind "ajax:complete", ->
      $('#edit_button_#{item.id}').attr 'disabled', false
      $('#item_operation_loading_#{item.id}').hide()
      $('#item_operation_#{item.id}').show()
    $("#edit_#{item.id}_form .action_date").datepicker()
.item{ id: "item_#{item.id}" }
  = form_for item, as: :entry, url: entry_path(displaying_month.year, displaying_month.month, item.id), remote: true, method: :put, html: { id: "edit_#{item.id}_form", class: 'well' } do |f|
    .row-fluid
      .alert= t('.edit_credit_item')
      = f.text_field :action_date, value: l(item.action_date), size: 12, placeholder: 'YYYY/MM/DD', id: "action_date_#{item.id}", class: %w(input-small action_date)
      = item.name.decorate
      %span
        = @user.all_accounts[item.from_account_id]
        \=&gt;
        = @user.all_accounts[item.to_account_id]
      %span
        = number_to_currency(item.amount)
    .row-fluid
      %span{ id: "item_operation_#{item.id}" }
        = f.submit t('button.save'), id: "edit_button_#{item.id}", class: %w'btn btn-primary'
        = link_to t('link.cancel'), entry_path(displaying_month.year, displaying_month.month, item.id), remote: true, method: :get, class: 'btn'
      %span{ id: "item_operation_loading_#{item.id}", style: 'display:none;' }= image_tag 'loading.gif', alt: 'loading...'
    .row-fluid
      %div{ id: "item_warning_#{item.id}" }

app/views/entries/_edit_item.html.haml
:coffeescript
  $ ->
    $('#edit_#{item.id}_form').bind "ajax:before", ->
      $('#edit_button_#{item.id}').attr 'disabled', true
      $('#item_operation_#{item.id}').hide()
      $('#item_operation_loading_#{item.id}').show()
    $('#edit_#{item.id}_form').bind "ajax:complete", ->
      $('#edit_button_#{item.id}').attr 'disabled', false
      $('#item_operation_loading_#{item.id}').hide()
      $('#item_operation_#{item.id}').show()
    $("#edit_#{item.id}_form .action_date").datepicker()
    $("#edit_#{item.id}_form .confirmation_required_label").bind "click", ->
      entries.toggleConfirmationRequired("#edit_#{item.id}_form")
    #initialize confirmation required just after rendering initialy
    entries.toggleConfirmationRequired("#edit_#{item.id}_form", _.contains(["1", "true"], $("#edit_#{item.id}_form .confirmation_required_field").val()))
.item{ id: "item_#{item.id}" }
  = form_for item, as: :entry, url: entry_path(displaying_month.year, displaying_month.month, item.id), remote: true, method: :put, html: { id: "edit_#{item.id}_form", class: 'well' } do |f|
    .row-fluid
      = f.text_field :action_date, value: l(item.action_date), size: 12, placeholder: 'YYYY/MM/DD', id: "action_date_#{item.id}", class: %w(input-small action_date)
      = f.text_field :name, placeholder: t('placeholder.item_name'), class: 'item_name'
      = RailsEmoji.render(':smile:', class: 'emoji_button').html_safe
      = f.hidden_field :confirmation_required, class: 'confirmation_required_field'
      %span.item_confirmation_not_required.confirmation_required_label= icon_no_confirmation
    .row-fluid.input-row
      = f.select 'from_account_id', @user.from_accounts, {}, class: %w'input-medium from_account_id'
      \=&gt;
      = f.select 'to_account_id', @user.to_accounts, {}, class: %w'input-medium to_account_id'
      %span.input-append
        = f.text_field 'amount', style: 'text-align: right;', placeholder: t('placeholder.amount'), class: %w(input-small amount)
        %span.add-on>= t('number.currency.format.unit')
      = f.text_field 'tag_list', placeholder: t('placeholder.tag'), class: %w(input-medium tag_list)
      %span{ id: "item_operation_#{item.id}" }
        = f.submit t('button.save'), id: "edit_button_#{item.id}", class: %w'btn btn-primary'
        = link_to t('link.cancel'), entry_path(displaying_month.year, displaying_month.month, item.id), remote: true, method: :get, class: 'btn'
      %span{ id: "item_operation_loading_#{item.id}", style: 'display:none;' }= image_tag 'loading.gif', alt: 'loading...'
    .row-fluid
      %div{ id: "item_warning_#{item.id}" }

app/views/entries/_item.html.haml
.item{ id: "item_#{item.id}", class: "row-fluid #{item_row_class(item)}" }
  .span2.item_date= l(item.action_date)
  .span3.item_name
    = item_row_confirmation_required(item, @tag, @mark, @keyword)
    %span.item_name_text= item_row_name(item)
    = link_to_tags(item)
  .span2.item_from= item_row_from_account(item)
  .span2.item_to= item_row_to_account(item)
  .span2.item_amount= number_to_currency(item.amount.abs)
  .span1.item_operation
    %span{ id: "navi_#{h item.id}" }= item_row_operation(item, @tag || @mark || @keyword)
    %span{ id: "loading_#{h item.id}", style: 'display: none;' }= image_tag 'loading.gif', alt: 'loading...'

app/views/entries/_new_item.html.haml
:coffeescript
  $ ->
    entries.itemNameObserver("#{entry_candidates_path}")
    $('#do_add_item')
      .bind('ajax:before', -> $('#new_add_button').attr('disabled', true))
      .bind('ajax:complete', -> $('#new_add_button').attr('disabled', false))
    $('#do_add_item .datepicker').datepicker()
    $('#do_add_item .confirmation_required_label').bind 'click', ->
      entries.toggleConfirmationRequired('#do_add_item')
= form_for it, as: :entry, url: entries_path(it.action_date.year, it.action_date.month), remote: true, method: :post, html: { id: 'do_add_item', class: 'well' } do |f|
  .row-fluid
    %ul.nav.nav-pills
      %li.active= link_to t('link.register_income_expense'), new_entry_path(year: it.action_date.year, month: it.action_date.month), remote: true, method: :get
      %li= link_to t('link.register_adjustment'), new_entry_path(year: it.action_date.year, month: it.action_date.month, entry_type: 'adjustment'), remote: true, method: :get
  .row-fluid.input-row
    = f.text_field :action_date, value: l(it.action_date), class: 'input-small datepicker', placeholder: 'YYYY/MM/DD'
    = f.text_field :name, placeholder: t('placeholder.item_name'), class: 'item_name'
    = RailsEmoji.render(':smile:', class: 'emoji_button').html_safe
    = f.hidden_field :confirmation_required, class: 'confirmation_required_field'
    %span.confirmation_required_label.item_confirmation_not_required= icon_no_confirmation
    = link_to t('.show_all_confirmation_required', mark: icon_confirmation).html_safe, mark_entries_path(mark: :confirmation_required)
  .row-fluid.input-row
    #candidates
  .row-fluid.input-row
    = f.select :from_account_id, @user.from_accounts, {}, class: %w(input-medium from_account_id)
    \=&gt;
    = f.select :to_account_id, @user.to_accounts, {}, class: %w(input-medium to_account_id)
    %span.input-append
      = f.text_field 'amount', value: (it.amount.nil? || it.amount == 0 ? nil : number_to_currency(it.amount, format: '%n')), class: 'amount input-small', placeholder: t('placeholder.amount')
      %span.add-on>= t('number.currency.format.unit')
    = f.text_field :tag_list, placeholder: t('placeholder.tag'), class: 'input-medium tag_list'
    = f.submit t('button.register'), id: 'new_add_button', class: 'btn btn-primary'
    = link_to t('link.about_emolett'), 'http://mayuco.github.com/emolett/', target: '_blank', class: 'trivial_link'
    = link_to t('link.about_emoji'), 'http://www.emoji-cheat-sheet.com/', target: '_blank', class: 'trivial_link'

app/views/entries/create_adjustment.js.haml
= render partial: 'items', locals: { items: items }
= render partial: 'success_message', locals: { selector: '#warning', message: t('message.register_successfully') + ' ' + l(item.action_date) + ' ' + t('label.adjustment') + ' ' + number_to_currency(item.adjustment_amount) }
= render partial: 'highlight_items', locals: { ids: updated_item_ids }
! $('#do_add_item .amount').val('');
! $('#do_add_item .tag_list').val('');
! $('#do_add_item #entry_to_account_id').focus();

app/views/entries/destroy.js.haml
= render partial: 'remove_items', locals: { ids: deleted_ids }
- item_name = item.adjustment? ? t('label.adjustment') : item.name
= render partial: 'success_message', locals: { selector: '#warning', message: "#{t('message.delete_successfully')} #{l(item.action_date)} #{item_name.decorate} #{number_to_currency(item.amount)}" }
= render partial: 'replace_items', locals: { items: updated_items }

app/views/entries/destroy_item.js.haml
= render partial: "remove_items", locals: { items: deleted_items }

- item_name = item.is_adjustment ? _('Adjustment') : item.name

= render partial: "success_message", locals: { selector: "#warning", message: "#{_('Item was deleted successfully.')} #{item.action_date.strftime("%Y/%m/%d")} #{item_name} #{CommonUtil.separate_by_comma(item.amount) + _('yen')}"}

= render partial: "replace_items", locals: { items: updated_items }

app/views/entries/index_for_remaining.js.haml
:plain
  $("#remains").fadeOut(#{GlobalSettings.effect.fade.duration}, function() {
    $("#remains").remove();
  });
  $("#items").append("#{j render(partial: 'item', collection: @items)}");

app/views/entries/index_with_filter_account_id.js.haml
:plain
  $("#items").html('');
  $("#items").append("#{j render(partial: 'item', collection: @items)}");
  $("#items").append("#{j render('remains_link')}");

app/views/entries/index_with_tag.html.haml
.row
  .span12
    #warning{:style => "color: red"}
    #itemlistarea
      %p#list_item_explain
        %h3= t("entries.income_outgoing_list")
        (tag: #{h @tag})
      = render 'items_header'
      #items
        - @items.each do |it|
          = render partial: 'item', locals: { event_item: it }
        = render 'remains_link'

app/views/entries/new.js.haml
:plain
  $("#input_item_area").hide();
  $("#input_item_area").html("#{j render(partial: (@item.adjustment? ? 'new_adjustment' : 'new_item'), locals: { it: @item })}");
  $("#input_item_area").fadeIn(#{GlobalSettings.effect.fade.duration});

app/views/entries/show.js.haml
:plain
  $("#item_#{@item.id}").hide();
  $("#item_#{@item.id}").replaceWith("#{j render(partial: 'item', locals: { item: @item })}");
  $("#item_#{@item.id}").fadeIn(#{GlobalSettings.effect.fade.duration});

app/views/entries/update.js.haml
= render partial: 'items', locals: { items: items }
- item_name = item.adjustment? ? t('label.adjustment') : item.name
= render partial: 'success_message', locals: { selector: '#warning', message: "#{t('message.save_successfully')} #{l(item.action_date)} #{item_name.decorate} #{number_to_currency(item.amount)}" }
= render partial: 'highlight_items', locals: { ids: updated_item_ids }