config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  root to: "login#login"

  match 'simple', to: 'entries#new', entry_type: 'simple', as: 'simple_input', via: :get
  resource(:login, path: 'login', as: 'login', controller: 'login', only: [:login, :do_login]) do
    get '/', action: 'login', on: :member
    post '/', action: 'do_login', on: :member
  end
  match 'logout' => 'login#do_logout', as: :logout, via: [:get, :post]
  resource(:create_user, path: 'create_user', as: 'create_user', controller: 'login', only: [:create_user, :do_create_user]) do
    get '/', action: 'create_user', on: :member
    post '/', action: 'do_create_user', on: :member
  end
  match 'confirm_user' => 'login#confirmation', as: :confirm_user, via: :get

  scope 'months/:year/:month' do
    resources :entries
    resources :profit_losses
    resources :balance_sheets
  end

  scope 'current' do
    resources :entries, as: 'current_entries'
    resources :profit_losses, as: 'current_profit_losses'
    resources :balance_sheets, as: 'current_balance_sheets'
  end

  %w( tag mark keyword ).each do |s|
    scope "/#{s.pluralize}/:#{s}", as: s.to_sym do
      resources :entries do
        resource :confirmation_required
      end
    end
  end

  resources :entries do
    resource :confirmation_required
  end

  resource :account_status
  resource :confirmation_status
  resource :tag_status
  resources :entry_candidates
  namespace(:admin) do
    resources :users
  end

  namespace(:settings) do
    resources :accounts
    resources :credit_relations
    resource :user
  end

  namespace(:api) do
    resources :entries
    resources :accounts
    resource :session
  end

  namespace(:chart_data) do
    resources :assets
    resources :budgets
    resources :yearly_budgets
    resources :yearly_assets
  end

  resources :emojis
end

app/controllers/common/entries.rb
# frozen_string_literal: true

module Common
  module Entries
    def self.included(base)
      base.class_eval do
        include Common::Entries::InstanceMethods
      end
    end

    module InstanceMethods
      def index
        @tag = params[:tag]
        @mark = params[:mark]
        @keyword = params[:keyword]

        case
        when params[:remaining]
          _index_for_remaining(displaying_month, @tag, @mark, @keyword)
        when !params[:filter_account_id].nil?
          _index_with_filter_account_id
        when @tag.present?
          _index_with_tag(@tag)
        when @mark.present?
          _index_with_mark(@mark)
        when @keyword.present?
          _index_with_keyword(@keyword)
        else
          _index_plain(displaying_month)
        end
      end

      def create
        _create_entry
      end

      def update
        id = params[:id].to_i
        @item, @updated_item_ids, @deleted_item_ids = Teller.update_entry(@user, id, arguments_for_saving)
      end

      def destroy
        item = @user.items.find(params[:id])
        _destroy_item(item)
      end

      def show
        @item = @user.items.find(params[:id])
      end

      private

      def arguments_for_saving
        return {} if params[:entry].nil?

        prms = {}
        params[:entry].each do |k, v|
          attr = k.to_sym
          prms[attr] = case attr
                       when :amount, :adjustment_amount
                         Item.calc_amount(v)
                       when :action_date
                         parse_str_to_date(v)
                       else
                         v
                       end
        end
        prms
      end

      def parse_str_to_date(str)
        Date.parse(str)
      rescue ArgumentError
        raise InvalidDate
      end

      def _index_with_filter_account_id
        _set_filter_account_id_to_session_from_params
        @items = get_items(month: displaying_month)
      end

      def _index_with_tag(tag)
        @items = get_items(tag: tag)
      end

      def _index_with_keyword(keyword)
        @items = get_items(keyword: keyword)
      end

      def _index_with_mark(mark)
        @items = get_items(mark: mark)
      end

      def _default_action_date(month_to_display)
        month_to_display == today.beginning_of_month ? today : month_to_display
      end

      def _set_filter_account_id_to_session_from_params
        account_id = params[:filter_account_id].to_i
        session[:filter_account_id] = account_id == 0 ? nil : account_id
      end

      def _index_plain(month_to_display)
        @items = get_items(month: month_to_display)
      end

      def _get_date_by_specific_year_and_month_or_today(year, month)
        action_date = nil
        begin
          action_date = Date.new(year.to_i, month.to_i) unless today.beginning_of_month == Date.new(year.to_i, month.to_i).beginning_of_month
        rescue ArgumentError
          action_date = today
        end
        action_date || today
      end

      def _create_entry
        Item.transaction do
          @item, affected_item_ids = Teller.create_entry(@user, arguments_for_saving)
          affected_item_ids << @item.try(:id)
          @updated_item_ids = affected_item_ids.reject(&:nil?).uniq
        end
      end

      def _destroy_item(item)
        Item.transaction do
          result_of_delete = Teller.destroy_entry(@user, item.id)
          @updated_items = result_of_delete[0].map { |id| @user.items.find_by_id(id) }.reject(&:nil?)
          @deleted_item_ids = result_of_delete[1]
          @item = item
        end
      end

      def from_accounts
        from_or_to_accounts(:from_accounts)
      end

      def to_accounts
        from_or_to_accounts(:to_accounts)
      end

      def from_or_to_accounts(from_or_to = :from_accounts)
        # FIXME
        # html escape should be done in Views.
        @user.send(from_or_to).map { |a| { value: a[1], text: ERB::Util.html_escape(a[0]) } }
      end

      def _index_for_remaining(month, tag = nil, mark = nil, keyword = nil)
        month_to_display = if tag.present? || mark.present? || keyword.present?
                             nil
                           else
                             month.beginning_of_month
                           end

        @items = get_items(month: month_to_display, remain: true, tag: tag, mark: mark, keyword: keyword)
      end

      # options variation
      #   remain: true: get remaining items which are not shown at first.
      #   tag: String
      #   mark: String
      def get_items(options = {})
        if options[:month].present?
          from_date = options[:month].beginning_of_month
          to_date = options[:month].end_of_month
        end
        @user.items.partials(from_date, to_date,
                             filter_account_id: session[:filter_account_id],
                             remain: options[:remain], tag: options[:tag], mark: options[:mark], keyword: options[:keyword])
      end
    end
  end
end

app/views/common/_chart_header.html.haml
/[if lte IE 8]
  = javascript_include_tag 'flot/excanvas.min.js'
= javascript_include_tag 'charts'

app/views/common/_menu.html.haml
:ruby
  if params[:year].blank? || params[:month].blank?
    e_path = current_entries_path
    pl_path = current_profit_losses_path
    bs_path = current_balance_sheets_path
  else
    e_path = entries_path(params[:year], params[:month])
    pl_path = profit_losses_path(params[:year], params[:month])
    bs_path = balance_sheets_path(params[:year], params[:month])
  end

  items_link = if params[:controller] == 'entries'
                 link_to t('.items'), e_path, style: 'background: white none repeat x scroll 0 0;'
               else
                 link_to t('.items'), e_path
               end

  pl_link = if params[:controller] == 'profit_losses'
              link_to t('.profit_loss'), pl_path, style: 'background: white none repeat x scroll 0 0;'
            else
              link_to t('.profit_loss'), pl_path
            end

  bs_link = if params[:controller] == 'balance_sheets'
              link_to t('.balance'), bs_path, style: 'background: white none repeat x scroll 0 0;'
            else
              link_to t('.balance'), bs_path
            end

  simple_input_link = link_to t('.simple_input'), simple_input_path
  config_link = link_to t('.config'), settings_accounts_path
  logout_link = link_to t('link.logout'), logout_path, confirm: t('message.logout_really')

= items_link + pl_link + bs_link + simple_input_link + config_link + logout_link

app/views/common/error.js.haml
:ruby
  id = @error_js_params[:id]
  errors = @error_js_params[:errors]
  default_msg = @error_js_params[:default_message]
  before = @error_js_params[:before]
  after = @error_js_params[:after]

!= before

! $('##{id}').attr('class', "alert alert-error");
- if errors.blank?
  ! $("##{id}").html("#{default_msg}");
- else
  ! $("##{id}").html("#{errors.to_a.join('<br/>')}");
! $('##{id}').effect('pulsate', { times:#{GlobalSettings.effect.pulsate.times} }, #{GlobalSettings.effect.pulsate.duration});

!= after

app/views/common/redirect.js.haml
! location.href = "#{j(@path_to_redirect_to)}";